---
- name: Install memcached server
  yum: 
    name: memcached-{{ memcached_version }}
    state: present
  become: true

- name: Configure memcached server 
  template:
    src: memcached.config.j2
    dest: /etc/sysconfig/memcached
    owner: root
    group: root
    mode: 0644
  become: true
  register: memcachedconf

- name: Start and enable memcached service
  service:
    name: memcached
    state: started
    enabled: true
  become: true

- name: Restart memcached if configurations are changed
  service:
    name: memcached 
    state: restarted
    enabled: true
  when: memcachedconf.changed
  become: true